### ISSUE TITLE
Direct access to server console (RCON planned)

### ISSUE THREAD

**Issue by CarbyDood** [nitrog0d/palworld-arm64#12]
Hello! Your docker container is working flawlessly for me on my oracle cloud instance! 

This isn't an issue, but i just wanted to ask if there is any way to actually access the server console that's in the container, for example to be able to force a world save, broadcast a message, or ban a player. Is there a way to do this? or to at least send a command to the server? Thank you for your time!

**Comment by nitrog0d** [comment]
This needs RCON to be set up, just like "automatic backups", it's on the plans

**Comment by nitrog0d** [comment]
Oh and you also can use the ingame /adminpassword and admin commands for now

**Comment by CarbyDood** [comment]
i see, thanks for the advice! awesome work on the container.

**Comment by sh-cho** [comment]
You can open RCON port in `docker-compose.yml` and edit `PalWorldSetting.ini` to change `RCONEnabled=True`.

```yaml
services:
  palword-servers:
    # snip
    ports:
      - '8211:8211/udp'
      - '25575:25575/tcp'  # add this
```
